version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./Backend
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
    restart: unless-stopped
    ports:
      - "80:80"
